更新EggMySQLInsertResult类型
eggjs/egg-mysql pull request #21
Opened 2022-10-14 02:51 UTC by hanjianheng

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

2022-10-14 04:19 UTC, hyj1991 commented on index.d.ts
> +  message: string;
> https://github.com/mysqljs/mysql/blob/master/lib/protocol/packets/OkPacket.js#L22

看 mysql 这个包的实现，`protocol41` 这几个不是一定会存在的

2022-10-14 08:39 UTC, hanjianheng commented on index.d.ts
> +  message: string;
type EggMySQLInsertResult = {
  affectedRows: number;
  fieldCount: number;
  insertId: number;
  serverStatus?: number;
  warningCount?: number;
  message: string;
  protocol41?: boolean;
  changedRows: number;
};
看了代码，我更改一下，您看一下是否正确.。
还有一点不太明白， EggMySQLUpdateResult 
![image](https://user-images.githubusercontent.com/42432644/195802578-eb07a2b5-b51b-4915-8757-51a9c72add4e.png)
 应该和InsertResult 保持一致吧

2022-12-13 12:26 UTC, AntiMoron requested changes

2023-03-06 13:56 UTC, fengmk2 commented
直接使用 ts 重构了 https://github.com/eggjs/egg-mysql/pull/27

2023-03-06 13:56 UTC, closed without merging